Harmonize logging levels.
BlueBrain/Search pull request #263
Opened 2021-03-01 14:00 UTC by EmilieDel

Fixes [BBS-256](https://bbpteam.epfl.ch/project/issues/browse/BBS-256).

This PR tries to harmonize the logging levels for every entrypoints.

2021-03-01 14:32 UTC, jankrepl approved these changes
Looks good:) 
BTW it seems like we are using mostly `INFO` level in our code.

```
$ git grep logger.info | wc -l
     200
$ git grep logger.debug | wc -l
      37
$ git grep logger.warning | wc -l
       7
$ git grep logger.error | wc -l 
       9
```

2021-03-09 09:02 UTC, pafonta commented on .env.example
> +# Integer values of Python logging levels are as follows (default is WARNING):
```suggestion
# Integer values of Python logging levels are as follows (default is INFO):
```

2021-03-09 09:05 UTC, EmilieDel commented on .env.example
> +# Integer values of Python logging levels are as follows (default is WARNING):
Good finding! Thanks @pafonta !

2021-03-09 09:06 UTC, pafonta requested changes
Oh, sorry, I forgot:

We need to update the `README` too.

Especially the command using `--verbose` and the first part of the NB mentioning it here:
https://github.com/BlueBrain/Search/blob/master/README.md#create-the-mining-cache

2021-03-09 09:28 UTC, EmilieDel commented
Really good point @pafonta! I am changing that this afternoon! Thanks!

2021-03-09 16:04 UTC, Stannislav commented
I just noticed we have `BBS_MINING_VERBOSE=-vv` in `.env.example`. This might be related to the changes introduced in this PR.

2021-03-09 16:25 UTC, EmilieDel commented
Thanks @Stannislav, it is really relevant for this PR. I tried to address your comment in 3bd5d1e.

2021-03-10 08:04 UTC, pafonta approved these changes

2021-03-12 13:25 UTC, merged